# Generated by Django 3.0.6 on 2022-07-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_num', models.IntegerField()),
                ('solved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_num', models.PositiveSmallIntegerField()),
                ('task_id', models.CharField(max_length=36)),
                ('submit_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.TextField(null=True)),
            ],
        ),
    ]
